name: merge_arb
description: Codegen that merges multiple ARB files into a single ARB file.
version: 0.3.1
repository: https://github.com/ltman/merge_arb

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

issue_tracker: https://github.com/ltman/merge_arb/issues

environment:
  sdk: ^3.9.0

dependencies:
  build: ^4.0.0
  glob: ^2.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  intl: ^0.20.2
